accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

score/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('score/', views.ListScoreView.as_view(), name='list-score'),
    path('score/search/', views.SearchScoreView.as_view(), name='search-score'),
    path('score/<int:pk>/detail/', views.DetailScoreView.as_view(), name='detail-score'),
    path('score/<int:pk>/pdf/', views.ScorePdfView.as_view(), name='score-pdf'),
    path('score/create/', views.CreateScoreView.as_view(), name='create-score'),
    path('score/<int:pk>/delete/', views.DeleteScoreView.as_view(), name='delete-score'),
    path('score/<int:pk>/update/', views.UpdateScoreView.as_view(), name='update-score'),
]

scoreproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('score.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

score/models.py
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField

CATEGORY = (
    ('課題曲', '課題曲'),
    ('クラシック', 'クラシック'),
    ('ポップス', 'ポップス'),
    ('アンサンブル', 'アンサンブル'),
)


class Score(models.Model):
    title = models.CharField(max_length=100, verbose_name="曲名")
    comp = models.CharField(max_length=100, verbose_name="作曲者")
    arr = models.CharField(max_length=100, blank=True, verbose_name="編曲者")
    category = models.CharField(max_length=100, choices=CATEGORY, verbose_name="ジャンル")
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ScoreFile(models.Model):
    score = models.ForeignKey(Score, on_delete=models.CASCADE)
    file_url = models.URLField(max_length=500, blank=True, null=True)
    file_type = models.CharField(max_length=50, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        title = self.score.title if self.score else "不明"
        return f"{self.score.title} - {self.file_type}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

accounts/views.py
from django.shortcuts import render

from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignForm

class SignupView(CreateView):
    model = User
    form_class = SignForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('index')

score/views.py
from django import forms
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator
from django.core.files.base import ContentFile
from django.db.models import Q
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    DeleteView,
    UpdateView,
    View,
)
from .models import Score, ScoreFile
from .consts import ITEM_PER_PAGE
#from .utils import detect_and_split_pages  # ← トリミング関数
import os
from cloudinary.uploader import upload
from io import BytesIO


class ListScoreView(ListView):
    template_name = 'score/score_list.html'
    model = Score
    paginate_by = ITEM_PER_PAGE

    def get_queryset(self):
        score_list = Score.objects.all()
        query = self.request.GET.get('query')
        query_title = self.request.GET.get('title')
        query_comp = self.request.GET.get('comp')
        query_arr = self.request.GET.get('arr')
        query_category = self.request.GET.get('category')
        sort = self.request.GET.get('sort', 'title')#表示順　デフォルトは曲名 

        #検索機能
        if query:#キーワード検索
            score_list = score_list.filter(
                Q(title__icontains=query) | Q(comp__icontains=query) | Q(arr__icontains=query) | Q(category__icontains=query)
            )
        else:#詳細検索
            if query_title:
                score_list = score_list.filter(title__icontains=query_title)
        
            if query_comp:
                score_list = score_list.filter(comp__icontains=query_comp)
        
            if query_arr:
                score_list = score_list.filter(arr__icontains=query_arr)
        
            if query_category:
                score_list = score_list.filter(category__icontains=query_category)
        
        
        allowed_sorts = ['title', '-title', 'comp', '-comp', 'arr', '-arr' ]
        if sort in allowed_sorts:
            score_list = score_list.order_by(sort)

        return score_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.request.GET.get('title', '')
        context['comp'] = self.request.GET.get('comp', '')
        context['arr'] = self.request.GET.get('arr', '')
        context['category'] = self.request.GET.get('category', '')
        context['sort'] = self.request.GET.get('sort','title')
        return context



#def post_list(request):
#    posts = Post.objects.all()
#    return render(request, 'blog/post_list.html', {'posts': posts})


class DetailScoreView(DetailView):
    template_name = 'score/score_detail.html'
    model = Score
    success_url = reverse_lazy('list-score')


class CreateScoreView(CreateView):
    model = Score
    fields = ['title', 'comp', 'arr', 'category']
    template_name = 'score/score_create.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        files = request.FILES.getlist('files')

        if form.is_valid():
            score = form.save()

            for file in files:
                try:
                    # Cloudinary にそのままアップロード
                    upload_result = upload(file, folder="scores/files", resource_type="raw")
                    file_type = getattr(file, 'content_type', 'unknown')

                    # DB に URL 保存
                    ScoreFile.objects.create(
                        score=score,
                        file_url=upload_result['secure_url'],
                        file_type=file_type
                    )
                except Exception as e:
                    print("Cloudinary upload failed:", e)

            return redirect('list-score')

        return self.form_invalid(form)


class DeleteScoreView(DeleteView):
    template_name = 'score/score_delete.html'
    model = Score
    success_url = reverse_lazy('list-score')

class UpdateScoreView(UpdateView):
    template_name = 'score/score_update.html'
    model = Score
    fields = ('title','comp','arr','category')
    success_url = reverse_lazy('list-score')

class IndexScoreView(TemplateView):
    template_name = 'score/score_index.html'
    model = Score
    success_url = reverse_lazy('detail-score')


#def index_view(request):
#    object_list = Score.objects.order_by()
#
#    paginator = Paginator(object_list, ITEM_PER_PAGE)
#    page_number = request.GET.get('page',1)
#    page_obj = paginator.page(page_number)
#    
#
#
#    return render(request, 'score/index.html', {'object_list': object_list, 'page_obj':page_obj },)

class ScorePdfView(DetailView):
    template_name = "score/score_pdf.html"
    model = Score

class SearchScoreView(View):
    template_name = "score/score_search.html"

    def get(self, request, *args, **kwargs):
        query_params = request.GET.urlencode()
        if query_params:
            url = reverse('list-score') + f'?{query_params}'
            return redirect(url)
        # パラメータがないときはテンプレートを表示
        from django.shortcuts import render
        return render(request, self.template_name)

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}


{% block content %}
  <form method="post" class="p-4 m-4 bg-light border border-succsess rounded form-group">
    {% csrf_token %}
    <input type="text" name="username" class="form-control my-4" place="ユーザ　ID">
    <input type="password" name="password1" class="form-control mt-4" place="パスワード">
    <input type="password" name="password2" class="form-control mt-4" place="パスワード確認用">
    <small class="mb-2 small text-danger d-block text-start">パスワードは８文字以上で設定してください。</small>
    {% if form.error %}
       <span class="mb-2 small text-danger d-block text-start">利用できないユーザ　IDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
  </form>
{% endblock content%}

score/templates/score/components/pagination.html
{% load querystring %}
{% if page_obj.has_other_pages %}
  <nav class="pagination">
    <ul>
      {% if page_obj.has_previous %}
        <a href="?{% querystring request.GET page=1 %}">先頭</a>
        <a href="?{% querystring request.GET page=page_obj.previous_page_number %}">前</a>
        <a>　</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          {% if num == page_obj.number %}
            <!--<li><strong>--><span class="current">{{ num }}</span> <!--num }}</strong></li>-->
          {% else %}
            <!--<li>--><a href="?{% querystring request.GET page=num %}">{{ num }}</a><!--</li>-->
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a>　</a>
        <a href="?{% querystring request.GET page=page_obj.next_page_number %}">次</a>
        <a href="?{% querystring request.GET page=page_obj.paginator.num_pages %}">最後</a>
      {% endif %}
    </ul>
  </nav>
{% endif %}

score/templates/score/index.html
{% extends 'base.html' %}

{% block title %}楽譜一覧{% endblock title %}
{% block h1 %}楽譜一覧{% endblock %}

 
{% block content %}
  {% for item in object_list %} <!--レイアウト-->
  <div class="card">
    <h5 class="card-header">{{ item.title }}</h5>
    <div class="card-body">
      {% if  item.arr == ""  %}
      <h5 class="card-title">作曲者：{{ item.comp }}</h5>
      {% else %}
      <h5 class="card-title">作曲者：{{ item.comp }}　編曲者：{{ item.arr }}</h5>
      {% endif %}

      <h6 class="card-title">{{ item.category }}</h5>
      <a href="{% url 'detail-score' item.pk %}" class="btn btn-primary">詳細へ</a>
    </div>
  </div>
  {% endfor %}
  {% include 'score/components/pagination.html' %}
{% endblock content %}

score/templates/score/score_confim_delete.html
{% extends 'base.html' %}

{% block title %}楽譜削除{% endblock title %}
 
{% block content %}
  <form method="post">
    {% csrf_token %}
    <button type="submit">{{ object.title }}を削除する</button>
  </form>
{% endblock content %}

score/templates/score/score_create.html
{% extends 'base.html' %}

{% block title %}楽譜作成{% endblock title %}
 
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <label>楽譜ファイルを選択（複数可）</label><br>
    <input type="file" name="files" multiple><br><br>
    <button type="submit" class="btn btn-primary">登録</button>　<a href="{% url 'list-score' %}" class="btn btn-primary">戻る</a>
  </form>
{% endblock content %}

score/templates/score/score_delete.html
{% extends 'base.html' %}

{% block title %}楽譜削除{% endblock title %}
 
{% block content %}
  <h5>この楽曲を削除しますか？</h5>
  <a>{{ object.title }}</a>
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">削除する</button>　<button><a href="{% url 'list-score' %}">戻る</a></button>
    <!--<input type="hidden" name="日付" value="Post.objects.filter(published_date__lte=timezone.now())"> -->
  </form>
  
{% endblock content %}

score/templates/score/score_detail.html
{% extends 'base.html' %}

{% block h1 %}{{ object.title }}{% endblock %}
 
{% block content %}
   <!--レイアウト-->
  <div class="p-4 m-4 bg-ligth border border-scuccess rounded">
    {% if  object.arr == ""  %}
      <h5 class="card-title">作曲者：{{ object.comp }}</h5>
    {% else %}
      <h5 class="card-title">作曲者：{{ object.comp }}　編曲者：{{ object.arr }}</h5>
    {% endif %}
    <h6 class="text-success">{{ object.category }}</h5>

    <a href="{% url 'score-pdf' object.pk %}" class="btn btn-primary">楽譜</a>
    <a href="{% url 'update-score' object.pk %}" class="btn btn-primary">編集</a>
    <a href="{% url 'delete-score' object.pk %}" class="btn btn-primary">削除</a>
    <a href="{% url 'list-score' %}" class="btn btn-primary">戻る</a>
  </div>
{% endblock content %}

score/templates/score/score_list.html
{% extends 'base.html' %}

{% block title %}楽譜一覧{% endblock title %}
{% block h1 %}楽譜一覧{% endblock %}



 
{% block content %}



  <!-- 並び替えフォーム -->
  <form method="get" style="margin-left: auto;">
    <label for="sort">並び替え:</label>
    <select name="sort" id="sort" onchange="this.form.submit()">
      <option value="title" {% if request.GET.sort == "title" %}selected{% endif %}>タイトル昇順</option>
      <option value="-title" {% if request.GET.sort == "-title" %}selected{% endif %}>タイトル降順</option>
      <option value="comp" {% if request.GET.sort == "comp" %}selected{% endif %}>作曲者昇順</option>
      <option value="-comp" {% if request.GET.sort == "-comp" %}selected{% endif %}>作曲者降順</option>
      <option value="arr" {% if request.GET.sort == "arr" %}selected{% endif %}>編曲者昇順</option>
      <option value="-arr" {% if request.GET.sort == "-arr" %}selected{% endif %}>編曲者降順</option>
    </select>

    <!-- 検索条件のhiddenフィールドで保持 -->
    <input type="hidden" name="title" value="{{ request.GET.title }}">
    <input type="hidden" name="comp" value="{{ request.GET.comp }}">
    <input type="hidden" name="arr" value="{{ request.GET.arr }}">
    <input type="hidden" name="category" value="{{ request.GET.category }}">
  </form>

  <!--検索ツール-->
    <h2>検索ツール</h2>
    <form action="" method="get">
      <input name="query" value="{{ request.GET.query }}" type="text" placeholder="キーワードを入れてください" /><button type="submit" class="btn btn-primary">検索する</button><br>
      <a href="{% url 'search-score' %}">詳細検索↗</a>
    </form>


  <!-- ページネーション -->
  {% include 'score/components/pagination.html' %}
  



<div class="row"><!--レイアウト-->

  <!--楽譜一覧-->
  {% for item in object_list %} 
  <div class="card">
    <a href="{% url 'detail-score' item.pk %}" class="card-header" >{{ item.title }}</a>
    <div class="card-body">
      {% if  item.arr == ""  %}
      <h5 class="card-title">作曲者：{{ item.comp }}</h5>
      {% else %}
      <h5 class="card-title">作曲者：{{ item.comp }}　編曲者：{{ item.arr }}</h5>
      {% endif %}

      <h6 class="card-title">{{ item.category }}</h5>
    </div>
  </div>
  {% endfor %}
</div>
{% include 'score/components/pagination.html' %}
{% endblock content %}

score/templates/score/score_pdf.html
{% extends 'base.html' %}
{% block title %}{{ object.title }} のPDF{% endblock %}
{% block content %}

<div class="row">
{% if object.scorefile_set.all %}
  {% for f in object.scorefile_set.all %}
    {% if "image" in f.file_type %}
      <div class="col-md-1">
        <a href="#" class="thumbnail">
          <img src="{{ f.file_url }}" width="350" alt="楽譜_image">
        </a>
      </div>
    {% elif "pdf" in f.file_type %}
      <div class="col-md-1">
        <a href="#" class="thumbnail">
          <iframe src="{{ f.file_url }}" width="300" height="400" alt="楽譜_PDF"></iframe>
        </a>
      </div>
      {% else %}
        <div class="col-md-1">
          <a href="{{ f.file_url }}" target="_blank">ファイルを開く</a>
        </div>
      {% endif %}
    </div>
  {% endfor %}
{% else %}
  <p>登録されたファイルはありません。</p>
{% endif %}
</div>
{% endblock %}

score/templates/score/score_search.html
{% extends 'base.html' %}

{% block h1 %}詳細検索{% endblock %}
<!--検索ツール-->
{% block content %}
<form action="" method="get">
    <table border="1">
    <tr>
        <th scope="col">曲名</th>
        <td><input name="title" value="{{ request.GET.title }}" type="text" placeholder="曲名を入れてください" /></td>
    </tr>
    <tr>
        <th scope="col">作曲者</th>
        <td><input name="comp" value="{{ request.GET.comp }}" type="text" placeholder="作曲者を入れてください" /></td>
    </tr>
    <tr>
        <th scope="col">編曲者</th>
        <td><input name="arr" value="{{ request.GET.arr }}" type="text" placeholder="編曲者を入れてください" /></td>
    </tr>
    <tr>
        <th scope="col">ジャンル</th>
        <td>
        <select name="category" value="{{ request.GET.category }}">
            <option value="課題曲">課題曲</option>
            <option value="クラシック">クラシック</option>
            <option value="ポップス">ポップス</option>
            <option value="アンサンブル">アンサンブル</option>
            <option value="その他">その他</option>
            <option selected value="">選択してください</option>
        </select>
        </td>
    </tr>
    </table>
    <button type="submit" class="btn btn-primary">検索する</button>　　<button type="button" class="btn btn-secondary" onclick="window.location.href='{{ request.path }}'">条件リセット</button>
</form>
{% endblock %}

score/templates/score/score_update.html
{% extends 'base.html' %}

{% block title %}楽譜修正{% endblock title %}
 
{% block content %}
  <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">修正する</button>　<button><a href="{% url 'list-score' %}">戻る</a></button>
  </form>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %} 吹奏楽</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-success sticky-top">
        <div class="navbar-nav d-flex flex-row">
            <a class="nav-link mx-3" href="{% url 'list-score' %}">楽譜一覧</a>
            <a class="nav-link mx-3" href="{% url 'create-score' %}">楽譜登録</a>
        </div>
        <div class="navbar-nav d-flex flex-row">
          {% if request.user.is_authenticated %}
            <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
          {% else %}
            <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
            <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
          {% endif %}
        </div>
    </nav>
    <div class="p-4">
        <h1>{% block h1 %}{% endblock %}</h1>
        {% block content %}{% endblock content %}
    </div>
  </body>
</html>